### ISSUE TITLE
Change data system services endpoint variable name in maap-api-nasa

### ISSUE THREAD

**Issue by abarciauskas-bgse** [MAAP-Project/maap-api-nasa#22]
Background:
* there is a 3d-tiles API endpoint in maap-api-nasa which points to an API gateway deployment managed by the data team, right now the deployment is managed by maap-data-system-services
* right now, that API gateway endpoint is configured for the api.maap-project.org/api/3d-tiles endpoint in settings.py as `DATA_SYSTEM_SERVICES_API_BASE` https://github.com/MAAP-Project/maap-api-nasa/blob/master/api/settings.py#L65-L66
* This is a confusing name since we will be deploying data system services as separate API gateways at this time

Proposed solution:
* Update DATA_SYSTEM_SERVICES_API_BASE to 3DTILES_API_ENDPOINT in settings.py

Tasks:
* Run maap-api-nasa locally. @philvarner most recently did this and said it was straight-forward.
* Update settings.py
* Make sure 3d-tiles endpoint still works, e.g. localhost:5000/3d-tiles/ATL08_ARD-beta___001/global/ept/ept-tileset/tileset.json returns the same thing as https://api.maap.xyz/api/3d-tiles/ATL08_ARD-beta___001/global/ept/ept-tileset/tileset.json
* Open PR against maap-api-nasa

**Comment by TonHai1111** [comment]
I just created a PR: https://github.com/MAAP-Project/maap-api-nasa/pull/23
