### ISSUE TITLE
Update log statement

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/maap-api-nasa#43]
There is a minor parameter ordering issue when generating log statements when sending the user status change email notification to admins:

```python
log.info("Sending '{} {} user' email for {} to JPL Admins ({})".format(
        member.get_display_name(),
        settings.EMAIL_JPL_ADMINS,
        template_key_user,
        template_key_status
    ))
```

should be 

```python
log.info("Sending '{} {} user' email for {} to JPL Admins ({})".format(
        template_key_user,
        template_key_status,
        member.get_display_name(),
        settings.EMAIL_JPL_ADMINS
    ))
```

**Comment by anilnatha** [comment]
@bsatoriu This is mark as resolved, but wasn't closed. When you have a moment, could you verify this change was rolled out so I can close this ticket?

**Comment by bsatoriu** [comment]
@anilnatha I verified this is deployed to ops.

**Comment by anilnatha** [comment]
Thanks Brian! I'm going to then close this ticket.
